<?php

namespace Database\Seeders;

use App\Models\News;
use App\Models\NewsCategory;
use Illuminate\Database\Seeder;

class NewsSeeder extends Seeder
{
    public function run(): void
    {
        $comunicazioni   = NewsCategory::where('slug', 'comunicazioni')->first();
        $eventi          = NewsCategory::where('slug', 'eventi')->first();
        $approfondimenti = NewsCategory::where('slug', 'approfondimenti')->first();

        $articles = [

            // ── Eventi ───────────────────────────────────────────────────

            [
                'news_category_id' => $eventi?->id,
                'title'            => 'Assemblea dei Delegati CAI 2026: appuntamento a Modena il 30 e 31 maggio',
                'slug'             => 'assemblea-delegati-cai-2026-modena',
                'excerpt'          => 'Il Club Alpino Italiano convoca l\'Assemblea dei Delegati 2026 a Modena, presso il BPER Forum "Guido Monzani". Due giornate dedicate alla vita associativa del CAI, tra bilanci, elezioni, cambiamenti climatici e futuro della montagna.',
                'body'             => '<p>Il Club Alpino Italiano ha ufficialmente convocato l\'Assemblea dei Delegati 2026, che si svolgerà sabato 30 e domenica 31 maggio presso l\'Auditorium del BPER Forum "Guido Monzani" di Modena.</p><p>L\'Assemblea rappresenta uno dei momenti più importanti della vita associativa del CAI, occasione di confronto e indirizzo strategico per il futuro dell\'associazione e delle sue strutture territoriali.</p><p>La giornata di sabato 30 maggio si aprirà con le attività istituzionali dedicate alla nomina del Presidente dell\'Assemblea e degli scrutatori, ai saluti degli ospiti e all\'approvazione del verbale dell\'Assemblea 2025. In programma anche importanti elezioni per il rinnovo di alcune cariche nazionali, tra cui il Vicepresidente Generale, i Probiviri Nazionali e i componenti del Comitato Elettorale.</p><p>Nel pomeriggio verranno affrontati i principali temi amministrativi e associativi, con la presentazione del Bilancio d\'esercizio 2025, la relazione annuale del Presidente Generale e gli interventi dei Delegati. Durante i lavori saranno inoltre conferiti riconoscimenti e onorificenze a figure di rilievo del mondo CAI.</p><p>La giornata di domenica 31 maggio sarà invece dedicata ad alcuni temi strategici per il futuro della montagna e dell\'associazione. Tra gli appuntamenti previsti figurano la relazione del prof. Greco sui cambiamenti climatici e la presentazione del "Manifesto CAI per il futuro della Montagna". È inoltre prevista la parte straordinaria dedicata alle modifiche allo Statuto del CAI.</p><p>A chiusura dell\'Assemblea saranno comunicati gli esiti delle votazioni e definite le quote associative per il 2027, oltre alla sede che ospiterà l\'Assemblea del prossimo anno.</p><p>Anche Montagna Servizi sarà presente all\'Assemblea dei Delegati con uno spazio dedicato all\'incontro con Delegati, Sezioni e Gruppi Regionali, per presentare i servizi e i progetti dedicati alla digitalizzazione e al supporto organizzativo del sistema CAI.</p>',
                'cover_image'      => 'news/news-assemblea-delegati-2026.webp',
                'published_at'     => '2026-05-21 09:00:00',
            ],

            [
                'news_category_id' => $eventi?->id,
                'title'            => 'CAI e Sentiero Italia CAI protagonisti all\'Italian Outdoor Festival 2026',
                'slug'             => 'cai-sentiero-italia-italian-outdoor-festival-2026',
                'excerpt'          => 'Il 9 e 10 maggio 2026 Montagna Servizi ha curato la presenza del Club Alpino Italiano all\'Italian Outdoor Festival di Milano, con uno stand dedicato al Sentiero Italia CAI. Due giornate con interesse concreto per il SICAI e la proiezione del documentario "Endless Peaks".',
                'body'             => '<p>Il 9 e 10 maggio 2026 Montagna Servizi ha curato la presenza del Club Alpino Italiano all\'Italian Outdoor Festival di Milano, allestendo e gestendo uno stand dedicato al Sentiero Italia CAI. Due giornate con profili di pubblico e dinamiche differenti, entrambe significative per la promozione del CAI e del suo progetto escursionistico più ambizioso.</p><h2>Sabato: lo stand al centro dell\'attenzione</h2><p>La giornata di sabato è stata quella con la maggiore affluenza. Fin dall\'apertura della fiera, lo stand ha attirato l\'interesse di molti visitatori, con domande concentrate su tre temi principali: il tracciato e le caratteristiche del Sentiero Italia, le modalità di iscrizione al CAI e i vantaggi associativi, le attività proposte dalle sezioni. Un pubblico con un\'età media stimata intorno ai 30-40 anni, in target sia per la diffusione della cultura escursionistica e alpinistica sia per l\'acquisizione di nuovi soci.</p><p>Lo stand era allestito con roll-up, bandiera e forex SICAI, guide e carte topografiche del Sentiero Italia, saggi e narrativa CAI, manuali di escursionismo e alpinismo, materiale promozionale e copie della Rivista CAI.</p><h2>Domenica: il documentario nel main stage</h2><p>La domenica, penalizzata dalla pioggia sul fronte affluenza alla fiera, ha offerto un momento di visibilità di segno diverso: nella mattinata è stato proiettato nel main stage il documentario "Endless Peaks" di Andrea Bandinelli con Francesco Tomé, produzione finanziata dal CAI. La proiezione ha riscosso buon interesse tra il pubblico presente, ampliando la presenza dell\'associazione oltre lo spazio fisico dello stand.</p><h2>Un bilancio positivo</h2><p>Il SICAI si conferma un progetto capace di generare interesse immediato non appena viene raccontato. L\'Italian Outdoor Festival rappresenta un contesto coerente con gli obiettivi di comunicazione del CAI: pubblico giovane, motivato, già orientato verso la montagna e l\'outdoor.</p>',
                'cover_image'      => 'news/news-italian-outdoor-festival-2026.webp',
                'published_at'     => '2026-05-21 09:00:00',
            ],

            [
                'news_category_id' => $eventi?->id,
                'title'            => 'Montagna Servizi alla fiera "Fa\' la cosa giusta!" — Milano, 13-15 marzo 2026',
                'slug'             => 'montagna-servizi-fa-la-cosa-giusta-2026',
                'excerpt'          => 'Dal 13 al 15 marzo 2026 Montagna Servizi ha partecipato alla fiera di Milano "Fa\' la cosa giusta!" all\'interno dello stand del Club Alpino Italiano, in un contesto dedicato alla sostenibilità, al turismo lento e alla cultura della montagna.',
                'body'             => '<p>Dal 13 al 15 marzo 2026 Montagna Servizi ha partecipato a "Fa\' la cosa giusta! 2026" all\'interno dello stand del Club Alpino Italiano, in un contesto dedicato alla sostenibilità, al turismo lento e alla cultura della montagna. Durante i tre giorni di fiera, lo spazio CAI è diventato un punto di incontro per soci, famiglie, scuole e appassionati, con attività rivolte a pubblici diversi e una forte attenzione alla divulgazione culturale ed educativa.</p><p>Montagna Servizi ha curato il supporto organizzativo e la gestione dello stand, contribuendo alla promozione dell\'editoria CAI attraverso la vendita di manuali, guide e pubblicazioni dedicate all\'alpinismo, all\'escursionismo, alla cultura della montagna e ai cammini.</p><p>Accanto all\'area editoriale, grande partecipazione hanno riscosso gli incontri e i laboratori per bambini promossi insieme a CAI Scuola, pensati per avvicinare le nuove generazioni ai temi dell\'educazione ambientale, della sostenibilità e della frequentazione consapevole della montagna.</p><p>Tra le attività più apprezzate dal pubblico anche la parete di arrampicata realizzata con il supporto della Società Escursionisti Milanesi, che ha permesso a bambini, ragazzi e visitatori di sperimentare in sicurezza un primo approccio all\'arrampicata, trasformando lo stand CAI in uno spazio dinamico e partecipato capace di coniugare cultura, sport e socialità.</p><p>L\'evento si conferma un\'importante opportunità di visibilità per il CAI e per Montagna Servizi, in un contesto fortemente orientato ai valori della sostenibilità e dell\'economia solidale.</p>',
                'cover_image'      => 'news/news-fa-la-cosa-giusta-2026.webp',
                'published_at'     => '2026-03-19 09:00:00',
            ],

            [
                'news_category_id' => $eventi?->id,
                'title'            => 'Il CAI al Salone Internazionale del Libro di Torino 2026',
                'slug'             => 'cai-salone-libro-torino-2026',
                'excerpt'          => 'Il Club Alpino Italiano, con il supporto operativo di Montagna Servizi, ha preso parte al Salone Internazionale del Libro 2026 di Torino. Incasso di € 6.186,70 con 411 articoli venduti, presentazioni editoriali e il contributo dei volontari della Sezione CAI Torino.',
                'body'             => '<p>Anche nel 2026 il Club Alpino Italiano, con il supporto organizzativo di Montagna Servizi, ha partecipato al Salone Internazionale del Libro di Torino, confermando l\'importanza della presenza del CAI in uno dei principali eventi culturali nazionali.</p><p>Lo stand CAI ha rappresentato uno spazio di incontro, divulgazione e promozione delle attività associative, attirando sia soci già vicini al Club Alpino Italiano sia nuovi visitatori interessati al mondo della montagna, dell\'escursionismo e della cultura alpina. Particolarmente apprezzato il contributo dei volontari della Sezione CAI Torino, che hanno supportato l\'accoglienza del pubblico e fornito informazioni sulle attività del territorio.</p><p>Grande interesse hanno suscitato le presentazioni editoriali organizzate presso la Sala della Montagna, dedicate ai volumi <em>Cose che capitano in montagna</em>, <em>Manuale di escursionismo base</em> e <em>Felik</em>, che hanno contribuito ad aumentare la partecipazione del pubblico e le vendite presso lo stand.</p><p>Nel complesso, lo stand CAI ha registrato un incasso di oltre € 6.186,70, con 411 articoli venduti — risultato superiore all\'edizione 2025 (€ 6.079,95 su 437 articoli) con un prezzo medio per articolo più alto, passato da circa € 13,91 nel 2025 a circa € 15,05 nel 2026. La giornata con maggiore affluenza ha registrato 119 articoli venduti e € 1.965,80 di incasso.</p><p>La partecipazione al Salone si conferma così un\'importante occasione per valorizzare il CAI non solo come realtà editoriale e culturale, ma anche come comunità associativa aperta al dialogo con il pubblico e il territorio.</p>',
                'cover_image'      => 'news/news-salone-libro-torino-2026.webp',
                'published_at'     => '2026-05-18 09:00:00',
            ],

            // ── Approfondimenti ──────────────────────────────────────────

            [
                'news_category_id' => $approfondimenti?->id,
                'title'            => 'Montagna Servizi e Veryfico: la rivoluzione digitale per la gestione delle Sezioni',
                'slug'             => 'montagna-servizi-veryfico-gestione-digitale-sezioni',
                'excerpt'          => 'Grazie alla nuova partnership, le sezioni potranno accedere a un software gestionale e contabile all\'avanguardia, integrato con il tesseramento e pienamente conforme alla normativa ETS.',
                'body'             => '<p>L\'evoluzione normativa legata al Terzo Settore (ETS) ha introdotto sfide burocratiche e contabili sempre più complesse per le realtà associative. Per rispondere a queste esigenze, Montagna Servizi propone ufficialmente alle sezioni l\'adozione di Veryfico (www.veryfico.it), la piattaforma gestionale nata per semplificare la vita dei dirigenti associativi.</p><h2>Un\'unica piattaforma, infiniti vantaggi</h2><p>Il punto di forza dell\'operazione risiede nell\'integrazione. Veryfico non è solo un software di contabilità, ma un ecosistema digitale che, una volta collegato alla piattaforma del tesseramento, permette di sincronizzare automaticamente i dati dei soci, gestire la contabilità con bilanci e rendiconti conformi agli schemi ministeriali per gli ETS, e centralizzare ogni aspetto della vita sezionale in un unico ambiente cloud sicuro.</p><h2>Conformità e trasparenza</h2><p>Con l\'introduzione del RUNTS e delle nuove scadenze fiscali, avere uno strumento che guidi nella corretta imputazione delle voci di spesa non è più un lusso, ma una necessità. Veryfico è progettato per garantire che la contabilità sia sempre "a prova di controllo", sollevando i tesorieri da incertezze normative.</p><p>L\'obiettivo di Montagna Servizi è chiaro: fornire strumenti tecnologici che riducano il tempo dedicato alla burocrazia, restituendo spazio alla missione associativa e alla passione per la montagna. Con Veryfico siamo ormai vicini alle prime 100 installazioni: un segnale concreto della fiducia che le Sezioni CAI stanno ripponendo in questo percorso.</p>',
                'cover_image'      => 'news/news-veryfico-2026.webp',
                'published_at'     => '2026-05-21 09:00:00',
            ],

            [
                'news_category_id' => $approfondimenti?->id,
                'title'            => 'Sentiero Italia CAI 2026: aggiornamenti, accreditamenti e il primo Premio Ambasciatori',
                'slug'             => 'sentiero-italia-cai-2026-aggiornamenti-premio-ambasciatori',
                'excerpt'          => 'Il Sentiero Italia CAI è protagonista di una fase di rivitalizzazione: nuovo portale con cartografia dinamica, procedura di accreditamento per le strutture ricettive, sviluppo territoriale con bandi europei e il lancio del Premio Annuale Ambasciatori del SICAI.',
                'body'             => '<p>Il Sentiero Italia CAI (SICAI) sta vivendo una fase di profonda rivitalizzazione. L\'obiettivo è elevare gli standard di fruizione lungo gli oltre 8.000 km di tracciato, rendendo l\'esperienza escursionistica più moderna, accessibile e integrata con i territori.</p><h2>Un nuovo portale per pianificare il percorso</h2><p>Il nuovo sito ufficiale è stato progettato per supportare l\'escursionista in ogni fase della pianificazione. Il cuore del portale è la cartografia dinamica, che permette una navigazione interattiva del sentiero con tracce GPS scaricabili per ogni singola tappa, filtri regionali per individuare eventi e iniziative locali, e strumenti ottimizzati per organizzare il proprio itinerario in autonomia.</p><h2>Accreditamento strutture e Passaporto del SICAI</h2><p>Il CAI ha definito una nuova procedura di accreditamento per le strutture ricettive, che include percorsi di formazione per gli operatori. Le strutture accreditate diventano i punti ufficiali per la timbratura del Passaporto del Sentiero Italia CAI — il nuovo documento ufficiale che certifica il percorso effettuato — ottenendo in cambio una maggiore visibilità sui canali ufficiali.</p><h2>Sviluppo territoriale e bandi</h2><p>Il Team del Sentiero Italia sta lavorando attivamente alla partecipazione a progetti europei, regionali e locali, con l\'obiettivo di finanziare interventi strutturali che facciano del sentiero un volano di sviluppo sostenibile per le aree interne.</p><h2>Il Premio Ambasciatori del Sentiero Italia CAI</h2><p>Nel 2026 è stata inaugurata la prima edizione del Premio Annuale Ambasciatori del Sentiero Italia CAI, un riconoscimento dedicato a coloro che si sono distinti per l\'impegno nella tutela e promozione del tracciato, confermando il SICAI come infrastruttura strategica per il turismo lento e la valorizzazione delle aree interne.</p>',
                'cover_image'      => 'news/news-sicai-2026.webp',
                'published_at'     => '2026-05-21 09:00:00',
            ],

            [
                'news_category_id' => $approfondimenti?->id,
                'title'            => 'Nuove norme fiscali 2026 per gli Enti del Terzo Settore: cosa cambia per le Sezioni CAI',
                'slug'             => 'nuove-norme-fiscali-2026-enti-terzo-settore-sezioni-cai',
                'excerpt'          => 'Dal 1° gennaio 2026 sono entrate in vigore le nuove disposizioni fiscali in materia di imposte dirette per gli ETS. Le Sezioni e i Gruppi Regionali CAI devono verificare il proprio inquadramento e adeguare i comportamenti fiscali. A cura di Montagna Servizi SCPA.',
                'body'             => '<p>Con la pubblicazione in Gazzetta Ufficiale del Decreto Legge 17 giugno 2025 n. 84 è stata definita la data di entrata in vigore delle norme fiscali sulle imposte dirette introdotte dalla Riforma del Terzo Settore (D.Lgs. 117/2017): <strong>1° gennaio 2026</strong>. Gli effetti riguardano sia gli enti iscritti al RUNTS sia quelli che non si sono ancora iscritti o che non si iscriveranno.</p><h2>Attività di interesse generale: quando sono non commerciali?</h2><p>Ai sensi dell\'art. 79, comma 2, del D.Lgs. 117/2017, le attività statutarie istituzionali si considerano di natura non commerciale — e dunque non imponibili fiscalmente — quando sono svolte a titolo gratuito oppure dietro versamento di corrispettivi che non superino i costi effettivi. Esiste inoltre una clausola di "piccolo margine" (art. 79, comma 2-bis): le attività di interesse generale restano non commerciali qualora i ricavi non superino di oltre il 6% i relativi costi per ciascun esercizio e per non oltre tre esercizi consecutivi.</p><h2>Il vantaggio dell\'APS</h2><p>La forma giuridica più conveniente risulta essere quella dell\'Associazione di Promozione Sociale (APS), in quanto consente di non considerare fiscalmente rilevanti i corrispettivi specifici versati dagli associati — ad esempio i contributi per escursioni o corsi — indipendentemente dal margine realizzato. L\'assunzione della qualifica di APS è subordinata all\'iscrizione al RUNTS.</p><h2>Chi non entra nel RUNTS</h2><p>Le Sezioni e i GR che decidono di non iscriversi al RUNTS non potranno più beneficiare della defiscalizzazione dei corrispettivi specifici nei confronti degli associati, poiché la Riforma elimina questa agevolazione per le associazioni culturali e di promozione sociale non iscritte. Anche la Legge 398/1991 — applicata da molte Sezioni per la tassazione forfetaria dell\'attività commerciale — sarà applicabile dal 2026 soltanto dalle associazioni e società sportive dilettantistiche.</p><h2>La raccomandazione di Montagna Servizi</h2><p>Si raccomanda a ciascuna Sezione e Gruppo Regionale di analizzare compiutamente le proprie caratteristiche operative sotto il profilo fiscale e di pianificare per tempo la transizione alle nuove regole. Il nostro team è a disposizione per una consulenza dedicata.</p>',
                'cover_image'      => null,
                'published_at'     => '2026-01-15 09:00:00',
            ],

            [
                'news_category_id' => $approfondimenti?->id,
                'title'            => 'Proroga IVA 2026 per gli enti associativi: cosa cambia e cosa no per le Sezioni CAI',
                'slug'             => 'proroga-iva-2026-enti-associativi-sezioni-cai',
                'excerpt'          => 'Il Consiglio dei Ministri ha prorogato di 10 anni le norme IVA agevolate per gli enti associativi. Ma attenzione: le nuove regole sulle imposte dirette restano in vigore dal 2026. Le Sezioni CAI devono verificare con cura il proprio inquadramento fiscale.',
                'body'             => '<p>Il Consiglio dei Ministri ha approvato in via definitiva il decreto con cui sono state prorogate <strong>per dieci anni</strong> le nuove norme IVA previste per gli enti associativi. Il quadro IVA rimane dunque inalterato almeno sino al 31 dicembre 2035.</p><h2>Cosa cambia con la proroga IVA</h2><p>La proroga consente alle associazioni di continuare a considerare non soggette ad IVA le cessioni di beni e prestazioni di servizi in favore dei soci a fronte di corrispettivi specifici, effettuate in conformità alle finalità istituzionali. Tra le categorie che beneficiano di questa agevolazione figurano le Associazioni di Promozione Sociale (APS), qualifica che molte Sezioni CAI stanno assumendo per massimizzare i vantaggi fiscali.</p><p>Attenzione: le Sezioni che non assumono la qualifica di APS e non rientrano nelle altre categorie indicate <strong>non potranno beneficiare del regime di esclusione IVA</strong>. I corrispettivi per escursioni, corsi in palestra, corsi di scialpinismo e simili saranno considerati di natura commerciale e soggetti ad IVA al 22%.</p><h2>Le imposte dirette: nessuna proroga</h2><p>Sul fronte delle imposte dirette (IRES e IRAP), <strong>non è stata prevista alcuna proroga</strong>. Le Sezioni e i GR entrati nel Terzo Settore godranno della fiscalità agevolata degli ETS, considerando non commerciali le attività istituzionali qualora i ricavi non superino di oltre il 6% i costi per ciascuna annualità e per non oltre tre annualità consecutive. Per le APS, i corrispettivi specifici degli associati restano non commerciali indipendentemente dal margine.</p><p>Le Sezioni che restano fuori dal RUNTS perderanno invece la defiscalizzazione dei corrispettivi specifici e non potranno più applicare la Legge 398/1991 (regime forfetario) se non sono anche ASD o SSD.</p><h2>Il consiglio di Montagna Servizi</h2><p>Invitiamo ancora una volta le Sezioni e i GR a valutare con attenzione l\'opportunità di procedere all\'iscrizione al RUNTS: rinunciare alla qualifica di ETS potrebbe comportare un sensibile aggravio degli oneri fiscali. Il nostro team è a disposizione per supportare l\'analisi e il percorso di adeguamento.</p>',
                'cover_image'      => null,
                'published_at'     => '2026-01-20 09:00:00',
            ],

            [
                'news_category_id' => $approfondimenti?->id,
                'title'            => 'Il bilancio delle Sezioni CAI nel Terzo Settore: quale modello adottare',
                'slug'             => 'bilancio-sezioni-cai-terzo-settore-quale-modello',
                'excerpt'          => 'Con l\'ingresso nel RUNTS le Sezioni e i GR CAI sono obbligati a utilizzare uno dei modelli di bilancio ministeriali. La scelta tra bilancio ordinario e rendiconto per cassa dipende dai proventi annui e dal possesso della personalità giuridica. A cura di Montagna Servizi SCPA.',
                'body'             => '<p>È tempo di bilanci per le Sezioni e i Gruppi Regionali CAI iscritti al RUNTS (Registro Unico Nazionale del Terzo Settore). Ecco una guida pratica per orientarsi tra i modelli obbligatori e le scadenze da rispettare.</p><h2>Chi non è nel RUNTS</h2><p>Le Sezioni e i GR non iscritti al RUNTS non sono obbligati a utilizzare uno schema specifico di bilancio e possono proseguire con i modelli già adottati (criterio di cassa, di competenza o misto). Se dotati di personalità giuridica regionale, il bilancio approvato va depositato presso il Registro Regionale delle Persone Giuridiche.</p><h2>I modelli obbligatori per chi è nel RUNTS</h2><p>Le Sezioni e i GR iscritti al RUNTS devono utilizzare uno dei modelli di cui al Decreto del Ministero del Lavoro del 5 marzo 2020:</p><ul><li><strong>Modello ordinario</strong>: Stato Patrimoniale, Rendiconto Gestionale e Relazione di Missione (Modelli A, B, C).</li><li><strong>Rendiconto per Cassa</strong> (Modello D): documento unico, utilizzabile al ricorrere delle soglie di legge.</li></ul><h2>Quale modello scegliere: le quattro casistiche</h2><ul><li>ETS <strong>senza personalità giuridica</strong> con proventi ≤ €300.000: può usare il Rendiconto per Cassa.</li><li>ETS <strong>senza personalità giuridica</strong> con proventi &gt; €300.000: deve usare il bilancio ordinario.</li><li>ETS <strong>con personalità giuridica</strong> con proventi ≤ €60.000: può usare il Rendiconto per Cassa.</li><li>ETS <strong>con personalità giuridica</strong> con proventi &gt; €60.000: deve usare il bilancio ordinario.</li></ul><p>Il riferimento per i proventi è l\'esercizio precedente: per il bilancio 2025, si guarda ai proventi 2024.</p><h2>Scadenze e deposito</h2><p>Il bilancio va depositato in via telematica presso il RUNTS entro <strong>180 giorni dalla chiusura dell\'esercizio</strong> (il bilancio 2025 deve essere depositato entro il 29 giugno 2026). I documenti vanno convertiti in formato PDF/A; la firma digitale non è obbligatoria ma è necessario il possesso di SPID. Gli ETS con proventi annui superiori a €1.000.000 devono redigere e pubblicare anche il <strong>bilancio sociale</strong>.</p><h2>Un adempimento più oneroso, ma più trasparente</h2><p>Con l\'avvento della Riforma del Terzo Settore gli adempimenti di bilancio hanno assunto connotati formali e sostanziali più onerosi. La contropartita è la trasparenza garantita dalla pubblicazione dei dati nel RUNTS. Montagna Servizi supporta le Sezioni in tutti gli adempimenti contabili e di deposito: contattaci per una consulenza dedicata.</p>',
                'cover_image'      => null,
                'published_at'     => '2026-02-07 09:00:00',
            ],

        ];

        News::truncate();

        foreach ($articles as $article) {
            News::create($article);
        }
    }
}
